### ISSUE TITLE
PipeFUSE sometimes fails when creating or listing of a large number (~100 000) of files 

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#1338]
**Describe the bug**
When we create or list a large number (~100 000) of files in PipeFUSE in S3 storage, at some point, the storage stops working correctly.  In all cases, the common mistake:
`cannot access '/storage_path/': Transport endpoint is not connected`

**To Reproduce**
1. Run a pipeline with mounted PipeFUSE in S3 storage
2. Create a large number (~100 000) of files in the created pipeline. Example command:
`
for j in {1..100000}; do 
 	head -c 500kB </dev/urandom > /path-to-storage/small/randfile$j.txt
done
`
3. List `ls /path-to-storage/small/ ` the created files in the storage, if the `2` step was a success. 

**Screenshots**
![image](https://user-images.githubusercontent.com/23356251/91552704-e3582f80-e934-11ea-813b-360ee1ccb634.png)

![image](https://user-images.githubusercontent.com/23356251/91552563-ae4bdd00-e934-11ea-8136-e168ce66cbcf.png)

![image](https://user-images.githubusercontent.com/23356251/91552890-2fa36f80-e935-11ea-95b2-ede9f6094583.png)

**Environment:**
 - Cloud Provider: **AWS**
 - Version **0.17.0.6626**
 - Browser: **chrome**

**Comment by tcibinan** [comment]
The error "Transport endpoint is not connected" is usually thrown if the underlying pipe fuse process is dead. It seems to be a typical out of memory failure. Once there are no enough memory for pipe fuse system OOM killer stops the process.

I've tried to reproduce the test case but there is no track of memory leaks in the process of creating lots of small files. At the same time several issues were discovered during the investigation which once resolved may eliminate the original issue.

First of all the described small files creation process happened after several 100GB files were created using the same pipe fuse process. As long as default pipe fuse [write file size limitation](https://github.com/epam/cloud-pipeline/pull/661#issue-317406254) is also 100GB such big files creation had failed leaving some of the resources not cleaned up. Therefore the issue seems to be partially resolved once #1328 is resolved.

At the same time whole small files creation process performs extremely bad invoking lots of ineffective calls to a cloud provider. Such additional workload caused additional memory consumption and also generated lots of garbage to be collected by python gc. Therefore the issue seems to be partially resolved once #1358 is resolved as well.

**Comment by tcibinan** [comment]
@kamyshova The testing scenario was performed with the current develop branch which includes changes introduced in #1364. Problems described in the issue seems to be resolved.
