### ISSUE TITLE
"Auto pause" function isn't working correctly

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#146]
__PART 1__
1. Login as admin
2. Open system "Settings" window, select "Preferences" tab
3. Click on "System" menu item in the left panel
4. Input into "system.max.idle.timeout.minutes" field value "2"
5. Input into "system.idle.action.timeout.minutes" field value "2"
6. Input into "system.idle.cpu.threshold" field value "30"
7. Input into "system.idle.action" field value "PAUSE"
8. Save changes
9. Logout, login as user
10. Open "Tools" page, select tool (e.g. "shell")
11. Set valid values into "Node type" and "Disk (Gb)"
12. Set "On demand" price type
13. Check that "Auto pause" checkbox is set
14. Set "Cmd template": ```sleep infinity```
15. Launch tool
16. Open run logs page of just-launched tool
17. Wait about ~15 min

__*Exp.*__: pipeline is being paused
__*Act.*__: pipeline is still working, not paused

__PART 2__
Repeat PART 1, on step 7 input value "PAUSE_OR_STOP"

__*Exp.*__: pipeline is being paused
__*Act.*__: pipeline is still working, not paused

**Comment by tcibinan** [comment]
Cloud pipeline auto-pause mechanism performs scheduled monitoring for idle machines. If there are some then the scheduled script tries to pause or stop them. There is an authentication problem while performing pause operation. 

Pause operation requires a node to have enough free space for storing temporary docker image. To check approximate temporary docker image size docker client is generated with `DockerRegistryManager.getDockerClient` method. The problem is that the method requires a user to be authorized in the security context but there is none while performing scheduled operation.

**Comment by tcibinan** [comment]
Corresponding e2e test has passed.

**Comment by NShaforostov** [comment]
Checked
