### ISSUE TITLE
Consider Cloud Providers' resource limitations, when scheduling a job

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#192]
**BACKGROUND**

Cloud Pipeline supports queueing of the jobs, that cannot be scheduled to the existing or new compute nodes immediately.
Queueing occurs if:
1. `cluster.max.size` limit is reached
2. Cloud Provider limitations are reached

If (1) happens - run will sit in the `init` state, until a spare will be available or stopped manually. This is the correct behavior.

But if (2) occurs - `nodeup.py` will receive an error from AWS and raise an exception, treating this as an issue with the node creation. Autoscaler will resubmit the node creation task for `cluster.nodeup.retry.count` times (default: 5) and then fail the job run.

This behavior confuses users, as (2) shall behave in the same manner as (1) - job shall be kept in the queue until there will be free space for a new node.

**TODOs**

1. `nodeup.py` shall handle instance/VM type/cores/RAM/SSD/etc. limitation exception for all three cloud providers (consider that Spots/Preemtibles may produce a different exception)
2. If such an exception is thrown - `nodeup.py` shall gracefully report such status to the autoscaler
3. Autoscaler shall not decrease current `cluster.nodeup.retry.count` counter value for such statuses
4. `nodeup.py` shall still report the exception to job log, so we can troubleshoot limits if needed

**Comment by sidoruka** [comment]
@mzueva , regarding the priorities across cloud providers - let's first implement for the `develop` (aws/azure) and then port the changes into GCP as well.

Hope there will be not much of such modifications, that require changes across different branches...

**Comment by mzueva** [comment]
@ekazachkova Please provide implementation of limit handling for AWS. 

1. Introduce exit code to `nodeup` script that will indicate that cluster scaling failed due to exceeding AWS instance quotas/limits. If `nodeup` process exits with this exit code, `AutoscaleManager` shall not increase retry count for runid and continue attempts to scale node up. 
2. Implement corresponding  changes to `nodeup` scripts for AWS provider. Do not forget to handle spot and ondemand instances creation.

For testing purposes I've requested to set limit for on-demand an to spot instances with type **m4.large** to 2 instances each. Also please consider that we should handle limit for total number of spot requests: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-spot-limits.html
