### ISSUE TITLE
GE Autoscaler shall respect CPU requirements of the job in the queue

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#298]
At the moment GE autoscaler treats each job in the queue as a `single-core` job.
But if one of the jobs was run using `-pe local 4` within a 2-cored machine - this will result in `unschedulable` jobs, that will wait in a queue forever (as autoscaler will setup a new 2-cored node).

We shall implement an approach, that allows processing the data even if the initial node type is not enough.

**Comment by sidoruka** [comment]
**Proposal**
1. If the autoscaler decides to scale-up, it shall check the maximum core required among the queued jobs (e.g. we have 3 jobs in `qwait`: with 2/8/1 cores requested)
2. Autoscaler than shall contact `/price` API and request the appropriate node type of the family, defined by the master node (e.g. master is run in AWS using `m5.xlarge`, then autoscaler shall setup `m5.2xlarge` to fulfill `max(2,8,1)`)
3. This behavior shall be customizable via `System parameters`:
- `CP_CAP_AUTOSCALE_HYBRID` - (bool) enables this `hybrid` cluster configuration
- `CP_CAP_AUTOSCALE_HYBRID_FAMILY` - (string) overrides the instance family to be used for the node type selection (e.g. if master is run using `m5.xlarge` and `CP_CAP_AUTOSCALE_HYBRID_FAMILY` is equal to `r5` - autoscaler shall create `r5.2xlarge` for the (2) example)

@mzueva @tcibinan I'd like to hear your opinion regarding this

**Comment by mzueva** [comment]
Some additions to the suggested approach

#### Algorithm of selecting a best matching node

- autoscaler detects that a new node shall be created, it checks the maximum cpu and ram requirements among all pending jobs
- list of all allowed instance types for current region is fetched from API `cluster/instance/allowed`
- all instance types not matching requirements are filtered out
- instances type are sorted by matching family, cpu, ram increasing and the first instance type is selected for run
- if no matching instance is present, autoscaler logs error message
- disk size for now is selected as master disk size

#### Scaling cluster down

- currently autoscaler scales down node only if job queue is empty
- autoscaler shall detect deadlock situation: a job is present in the queue with cpu requirement `8`, an idle node is present in the cluster with `4` cpu available, cluster is limited to size `1`
- if current cluster == maximum cluster size and idle nodes exist and it does not match any of pending jobs => such idle node shall be scaled down

#### TBD 

- for some workload cases it would be more effective to consider not maximum resource requirement but sum of requirements - in this case will create one large node instead of scaling 3 nodes. Possible pitfalls: for jobs with large requirements, sum may exceed available computational resources and we'll have to fallback to maximum approach or somehow recalculate instance parameters
- gpu support
- disk requirements support

**Comment by tcibinan** [comment]
Some additional thoughts to consider.

By default GE scheduler tries to submit jobs to a host with the minimal load within the cluster. It works fine for fixed size cluster because all the nodes are similarly occupied. Nevertheless, it doesn't work well with the autoscaled cluster. If there are several machines in the cluster GE will try to occupy each one of them preventing GE autoscaler from scaling down even if there are no many submitted jobs. The described situation leads to a significant resources redundancy.

To optimize the average cluster workload and reduce the redundant expenses GE scheduler job submission strategy should be altered. More information on the submission strategy can be found in the corresponding [man page](http://gridscheduler.sourceforge.net/htmlman/htmlman5/sched_conf.html).

**Comment by SilinPavel** [comment]
@sidoruka @mzueva @tcibinan 
I have tried to summarize all points that was mentioned here. 
I also have tried to build some code scratches  to be more specific in how this feature can be realized.

## The main steps

### Pre-requested changes

New System parameters of run:

-  CP_CAP_AUTOSCALE_HYBRID
-  CP_CAP_AUTOSCALE_HYBRID_FAMILY - if doesn't exist, we should use family of the master node

### Scale-up algorithm changes

- If the autoscaler decides to scale-up, it shall check the maximum core required among the queued jobs (e.g. we have 3 jobs in qstat: with 2/8/1 cores requested)
- List of all allowed instance types for current region is fetched from API cluster/instance/allowed
- All instance types not matching requirements are filtered out
- Instances type are sorted by matching family, cpu, ram increasing and the first instance type is selected for run
- If no matching instance is present, autoscaler logs error message
- Else autoscaler than shall request the appropriate node type of the family
     - first approach get max(2,8,1)  (autoscaler shall setup m5.2xlarge to fulfill )
     - second approach get sum(2,8,1) (autoscaler shall setup m5.4xlarge to fulfill)
- Point 6 should consider value of pe `allocation_rule` field:
     - $pe_slots means that all slots should be run on one node, so node with appropriate cpu should be run
     - $fill_up or $round_robin means that job could be run on several nodes, so we need to count how much available slots do we have and run only rest of it.
- Disk size for now is selected as master disk size

### Scale-down algorithm changes
- if current cluster == maximum cluster size and idle nodes exist and it does not match any of pending jobs => such idle node shall be scaled down 

## Code scratches
*NOTE* This code doesn't manipulate real objects from autosacale_sge.py. The main goal is to show how (in which steps) job could be done.

**Main skeleton of autoscale algorithm**
```
pending_jobs = [job for job in jobs if job.state == GridEngineJobState.PENDING]
running_jobs = [job for job in jobs if job.state == GridEngineJobState.RUNNING]
additional_hosts = load_hosts()
 
// run scale_down if needed
if now >= latest_running_job.datetime + scale_down_timeout:
        free_hosts = get_free_hosts(running_jobs, additional_hosts)
        // will check which of free hosts are unsuitable for pending jobs, so we can terminate it
        redundant_hosts = get_unsuitable_hosts(pending_jobs, free_hosts)
        // This method will just terminate all redundant hosts
        scale_down(running_jobs, redundant_hosts)
 
if pending_jobs:
    if len(additional_hosts) < max_additional_hosts:
        allowed = filter_by_family(pipe_api.get_allowed_instances())
        throw_if_allowed_is_empty(allowed)
        // will get instance that has >= cpu then sum of slots pending jobs, or if sum > -> will get powerful one from allowed
        instance_type = get_appropriate_instance(running_jobs, pending_jobs, additional_hosts, allowed)
        throw _if_instance_type_is_null(instance_type)
        scale_up(instance_type)
```

**Code to determinate appropriate instance type to be scaled up**
```
def get_appropriate_instance(running_jobs, pending_jobs, additional_hosts, allowed):
    avl_slots_by_hosts = get available_slots_by_hosts(running_jobs, additional_hosts)
    pending_jobs.sort_by_slots_desc
    allowed.sort_by_slots
    max_allowed = allowed[allowed.size - 1]
    total_slots = 0
     
    for job in pending_jobs:
        requested_slots = job.slots
         
        switch allocation_rule:
            case "$pe_slots":
                if requested_slots > max_allowed.cpu:
                      cancel_job_and_warn(job)
                      break
                total_slots += requested_slots
            case "$fill_up" or "$round_robin":
                for host, slots in avl_slots_by_hosts:
                    avl_slots_by_hosts[host] = requested_slots > slots ? 0 : slots - requested_slots
                    requested_slots = requested_slots > slots ? requested_slots - slots : 0 
                    if requested_slots == 0:
                        break
 
        if total_slots > max_allowed.cpu
            return max_allowed
    return allowed.filter(i -> i.cpu > total_slots).limit(1).get()
```

**Possible way to get unsuitable_nodes to be terminated**

```
def get_unsuitable_hosts(pending_jobs, free_hosts):
    if is_empty(pending_jobs):
        return free_hosts
     
    available_host_slots = {host, host.cpu in free_hosts}
    usable = []
    for job in pending_jobs:
        allocation_rule = job.allocation_rule
        job_slots = job.slots
         
        switch allocation_rule:
            case "$fill_up" or "$round_robin":
                for host, cpu in free_hosts:
                    job_slots = job_slots - available_host_slots[host]
                    if if host.avaliable_cpu > job_slots:
                        available_host_slots[host] = available_host_slots[host] - job_slots
                        job_slots = 0
                    else:
                        available_host_slots.delete(host)
                        job_slots = job_slots - cpu
                    usable.append(host)
                    if job_slots == 0:
                        break
             case default:
                    break
    return intersection(free_hosts, usable)
```

**Comment by tcibinan** [comment]
Thanks @SilinPavel.

Just wanted to point out several concerns.

Regarding the scale up scenario with no suitable instance types. I suppose we can make use of fail-fast approach. In most cases it is better to fail beforehand. For example, if a job was submitted in *pe_slots* queue with the requirement of 10000 cpus then we could just fail the job because it won't be executed anyway. Could you please take a look at SGE docs to find out how we can reject such jobs on the grid engine level? Anyway we can just kill the jobs right in `autosacale_sge.py` but lets investigate out options here.

Please keep in mind that a list of pending jobs actually will be a list of expired jobs that are in queue for more than `scale_down_timeout`. As long as we take it into account we can at least simplify `get_unsuitable_hosts` method for `pe_slots` case because we don't need to calculate if the host is suitable or not. It is not. Otherwise it will be occupied. At the same time `fill_up` case requires additional calculations, yeah.

**Comment by SilinPavel** [comment]
@tcibinan Regarding the first scenario with impossible requirements of the job, yes, probably we should reject such jobs and log this accident for a user.
And yes, for the case of parallel environment with allocation_rule = `$pe_slots` we can just say that this host should be terminated, indeed. Thanks for the review.

**Comment by tcibinan** [comment]
It just came to my mind that we can simplify `get_unsuitable_hosts` even further. We don't have to calculate if the host is suitable or not for `fill_up` case as well. The only difference is that **all hosts are suitable** by default in `fill_up` case. Otherwise there won't be any pending jobs.

**Comment by tcibinan** [comment]
Just referencing related issue #494. Probably it can be implemented along with all other SGE issues.

**Comment by tcibinan** [comment]
@NShaforostov Could you please take a look at the updated Grid Engine autoscaler? Notice that [the corresponding docs](https://cloud-pipeline.com/manual/Appendix_C/Appendix_C._Working_with_autoscaled_cluster_runs/) were updated as well. It includes information on how to launch hybrid clusters using system parameters. Probably you can tell what can be improved in the docs as well.

**Comment by NShaforostov** [comment]
@tcibinan I've verified. Previous issues (described as comments to #817) are fixed. Other functionality works great.
Docs look well. If I have additional ideas on this matter - I will let you know.
