### ISSUE TITLE
GCP: Incorrect behavior while trying to create FS mount

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#560]
The correct path for FS mount in GCP is `[IP_ADDRESS]:/[FILESHARE] [MOUNT_POINT_DIRECTORY]`.

### Part 1
Currently, if a host in "Cloud Regions" settings has a view just like `[IP_ADDRESS]` and you try to create FS mount by entering only `[MOUNT_POINT_DIRECTORY]` into the "**Storage path**" field, an error will occur, but sometimes (could not identify the cause) that error doesn't occur and FS mount is being created, e.g.:
1. ![1](https://user-images.githubusercontent.com/45459424/62064934-9f2cc400-b236-11e9-834b-f25edb9c2a80.png)
2. ![2](https://user-images.githubusercontent.com/45459424/62064946-a522a500-b236-11e9-968c-425edc0a6d0b.png)

When trying to create a file in the root of such FS mount an exception is being thrown:
![3](https://user-images.githubusercontent.com/45459424/62064857-74427000-b236-11e9-81ee-b155303cbab8.png)

When trying to delete such FS mount an error occurs:
![4](https://user-images.githubusercontent.com/45459424/62065181-22e6b080-b237-11e9-9ef2-fbd0af8a5eb5.png)
"**Unregister**" operation is being performed normally.

### Part 2
If a host in "Cloud Regions" settings has a view like `[IP_ADDRESS]:/[FILESHARE]` and you try to create FS mount by entering `[MOUNT_POINT_DIRECTORY]` into the "**Storage path**" field, FS mount is being created, but it has incorrect path e.g.:
1. ![5](https://user-images.githubusercontent.com/45459424/62065837-858c7c00-b238-11e9-803a-b6ab2f3eee59.png)
2. ![6](https://user-images.githubusercontent.com/45459424/62065998-d7350680-b238-11e9-9499-baf0f25f2172.png)

When trying to delete such FS mount an error occurs:
![7](https://user-images.githubusercontent.com/45459424/62066201-51fe2180-b239-11e9-9123-8dbc5879eea0.png)
"**Unregister**" operation is being performed normally.

**Comment by rodichenko** [comment]
@NShaforostov GUI does not support `[IP_ADDRESS]:/[FILESHARE]` format for FS mount hosts for now, it takes this root **as is** and adds `:/[MOUNT POINT DIRECTORY]`, which leads to **Part 2** error.

As for **Part 1**, the error is caused by incorrect path - like you said - it should be `[IP_ADDRESS]:/[FILESHARE]/[MOUNT_POINT_DIRECTORY]` for GCP.

**To be implemented**:
- **Cloud regions management dialog**: GUI shall support `[IP_ADDRESS]:/[FILESHARE]` format for GCP FS mount hosts;
- **FS Mount creation dialog** shall handle this path format correctly (without extra **:/** symbols).

**Comment by rodichenko** [comment]
@NShaforostov fixed, can you re-check this issue please?

**Comment by NShaforostov** [comment]
Verified. Fixed
