### ISSUE TITLE
Support AWS EC2 Instance Role Credentials

### ISSUE THREAD

**Issue by SilinPavel** [epam/cloud-pipeline#673]
AWS provides opportunity to user EC2 roles to be able to login into the cloud from ec2 instance (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html)

In order to support this future we need to review all communication with AWS to understand what should be change to be able to work with EC2 role credentials (Most of the functionality should work out of the box because of default credentials provider chain, but some of the feature like mounting buckets to a run instance and using cloud credentials on a run instance in general should be reviewed).

**Comment by SilinPavel** [comment]
Mounting bucket on a run instance:

As for now we fetch cloud credentials from env vars when mount s3 storages to run instances.
There 2 scenarios is possible:
1) In cloud region explicitly specified profile - if it so credentials from this profile will be passed to the instance
2) Cloud region doesn't have credentials profile - in this case default credentials chain will be used

When ec2 instance role is used in scenario 2 after some times credentials will be invalidated, so all mounted buckets wouldn't be reachable. 

We should introduce new approach to mount buckets on a run instance when ec2 role credentials is used (f.e. implement refreshable mechanism of fetching this creds from api)

**Comment by mzueva** [comment]
@SilinPavel Currently we observe that using instance role credentials for AWS authorization breaks only S3 bucket mounts. In order to fix this:
1. Introduce an environment variable `CP_USE_PIPE_MOUNT`, if it set to `true` use `pipe storage mount` command for S3 mounts
2. If API is currently using instance role credentials (determine by setting specific `SESSION_TOKEN`? container variable), try to mount  S3 buckets using `pipe storage mount`
