### ISSUE TITLE
Allow to restrict the visibility of the jobs

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#759]
**Background**
At the moment, Cloud Pipeline inherits the jobs' permissions from the parent object (e.g. from a pipeline or a tool). E.g.:
* `user1` launches `tool1` with run id `123`
* `tool1` is readable by `user2`
* `user2` is able to see the the run with id `123`

In certain use cases, this is not desired and shall be limited.

**Approach**
The following behavior shall be implemented to restrict the visibility of the jobs:
* There shall be a global preference that shall switch behavior:
  * Inherit (current approach, when the visibility is controlled by the tool/pipeline permissions)
  * Only owner (when only the person who launch a job can see it). Shall be set as a default for the Cloud Pipeline environment
* This can be also controlled per user/group (we shall add the same preference to the user/group profile configuration)
* Admins shall see everything for both cases as now

**Comment by sidoruka** [comment]
This shall be backported to `release/0.15`

**Comment by mzueva** [comment]
@sidoruka Just a minor clarification: `Pipeline runs` inherit permissions only from `Pipelines`, tool runs are visible only to owner and admins.

**Comment by mzueva** [comment]
Implemented via #769

**Comment by rodichenko** [comment]
GUI part implemented via ef281ef6fc679d5a73c077f5c4b51bcd4238abdf

**Comment by rodichenko** [comment]
@sidoruka backported to `release/0.15` via de47c0aa9a48151f49d5948b5f273de6a6b0e361

**Comment by NShaforostov** [comment]
I tried to verify this feature. It works well for users.
But I can't verify it for groups or global for Platform. I suppose that **Jobs visibility** dropdown box works not fully correct (for user or group) - it should be possible to leave this field empty (without value - e.g. how it done for **Allowed price types**). Otherwise, due to priority rule (global - group - user) the visibility of any pipeline run is always set only by value of this setting for a user.

@rodichenko can you fix it?

**Comment by NShaforostov** [comment]
Docs updated via #860

**Comment by rodichenko** [comment]
@NShaforostov fixed, backported to `release/0.15` via 439238db7a7051dc4bcd620310b97fe54a20ae1b

**Comment by NShaforostov** [comment]
@rodichenko thanks! Verified. Now, it works correctly.
