### ISSUE TITLE
Allow to view the historical resources utilization

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#857]
**Background**
At the moment, Cloud Pipeline allows viewing the detailed history of the resource utilization for each specific **active** job (thanks to #168).
But once the job is stopped - the information is not available anymore for the users. The utilization data is still stored in the ES indices for a preconfigured period of time (`system.resource.monitoring.stats.retention.period`, defaults to 5 days), but is not exposed via the API/GUI.

We shall allow the users to access this information after the job has been stopped for debugging/optimization purposes.

**Approach**
* Users shall be able to navigate to the specific job's resource utilization page (data shall be filtered by the job id and a corresponding period of time)
* Users shall be able to export the utilization information into a CSV file. This is required, if the user wants to keep the information for a longer period of time than defined by `system.resource.monitoring.stats.retention.period`.

**Comment by mzueva** [comment]
Regarding CSV export:

1. All metrics shall be exported in a single table: add a separate column for each disk/network interface
2. Add a new API method to export CSV with signature similar to /cluster/node/{name}/usage, with only difference that it shall also accept an `interval` between two timestamps in seconds, e.g. `1 second` - means that we return stats for every second `from` - `to`
3. Method shall write csv content directly to response, see `MetadataEntityController.downloadEntityAsFile`

**Comment by mzueva** [comment]
@rodichenko API for csv report is merged into develop: `GET /cluster/node/{name}/usage/report`

**Comment by rodichenko** [comment]
@mzueva thank you!
@sidoruka GUI part implemented (b121af131fc20ff12912bd010a5b7e350ee08675)

**Comment by NShaforostov** [comment]
I've tried to verify this feature. In general, it works.

@rodichenko minor notes:
1. In some cases, when I click the **Export** button and in the "intervals" list there are several items - the error message appears and a file isn't downloaded automatically:
![image](https://user-images.githubusercontent.com/45459424/74845603-50648a00-5340-11ea-9f5c-e208eb11b8b2.png)
I'm not sure in which cases this behavior appears, but in most of them in the "intervals" list were more than 3 items.
2. If the user tries to view the resources monitor of the completed run's node and the `system.resource.monitoring.stats.retention.period` is over - the monitor will be empty. It's OK. But the **Export** button will be available too. This situation can confuse the user - because he could wish to export utilization data (especially, when he'll view that the "intervals" list is not empty) - but any file he'll export will be empty.
Probably, we should disable the **Export** button for the completed runs if `system.resource.monitoring.stats.retention.period` is over?

**Comment by NShaforostov** [comment]
Docs were updated via #991

**Comment by rodichenko** [comment]
@NShaforostov fixed by #1128, could you verify this please?

**Comment by NShaforostov** [comment]
@rodichenko, verified. Works nice
