### ISSUE TITLE
Missing region while price loading

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#93]
On the launch page, while calculating a price the CP client calls `/pipeline/price` API method without specifying `regionId` parameter. This way the server calculates price for the specified instance type in any of the available regions. In practice, requested price may vary from region to region.

Therefore, `regionId` parameter should be specified explicitly.

**Comment by sidoruka** [comment]
@tcibinan can you double check: shall the same be fixed for the `pipe-cli` or it already calls `/price` correctly?

**Comment by sidoruka** [comment]
To sum this up:
1. GUI is fixed in bc2ec23 (region id is sent when a user changes it explicitly, for default run, e.g. dashboard, default region is used)
2. pipe-cli works correctly and passes region id if specified by the user
3. API does not use default region id if it is not passed explicitly, instead a random region is used
