### ISSUE TITLE
Upload & edit & delete storage buttons display when user haven't write/execute permissions

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#94]
- Cloud environment: AWS
- Version: 0.15.0.296.72d146bf70c408efd75911d31183caabb612c96a
- Steps to reproduce:
1. Create or select existing storage
2. Create or select folder in the storage
3. Click on gear-icon at top of the storage page
4. Click on "Permissions" tab in an appeared pop-up window
5. Click on "Add user" button, input a user name in an appeared pop-up window, confirm by click OK button
6. Click on an appeared row with the user name from step 5
7. Set permissions for the selected user: READ - allow, WRITE - deny, EXECUTE - deny
8. Logout
9. Login as the user from step 5
10. Open library
11. Open the storage

![image](https://user-images.githubusercontent.com/23356251/55802069-23203c00-5ae0-11e9-832e-b1147d02a788.png)

Expected: "Upload" button doesn't display, delete-icon and edit-icon for the folder don't display
Actual: Upload & edit & delete storage buttons display

**Comment by mzueva** [comment]
It seems that some problem exists with `pipeline.jar` binary that is produced by Travis builds. Part of security aspects related to setting permission mask for datastorage are not working (all other entities work fine). I've checked the develop branch build (produced by `gradlew build`) and intermediate Travis jar (before repackaging) and both jars work fine - issue is not reproduces. We need to check script `travis_repackage_dist.sh` to be sure that problem is in this part of the build process.

**Comment by sidoruka** [comment]
Fixed in 10cf757
@kamyshova please verify and reopen this issue if problem is still present
